In [210]:
import numpy as np
import time

In [211]:
#Using lists we can make multidimentional array but using numpy it will be easy
#numpy is array orieneted programming
a=np.array([0,1,2,3])   # takes input as list and creates to numpy array
print(a)

[0 1 2 3]

In [212]:
type(a)

numpy.ndarray

In [213]:
a.shape

(4,)

In [214]:
print(np.arange(12)) # create numpy array from 0 to 11

[ 0  1  2  3  4  5  6  7  8  9 10 11]

<h2>![WhatsApp Image 2024-05-30 at 7.46.20 PM.jpeg]()List vs Numpy Array speed </h2>

In [215]:
L=range(1000)  #0,1,2,3,4...999
# %timeit is function to calculate time per iteration
%timeit [i**2 for i in L]  #0,1,4,9,...999*999

299 µs ± 6.78 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [216]:
a=np.arange(1000)   #numpy is fast and memory effiecient
%timeit a**2

1.53 µs ± 359 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [217]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [218]:
a.ndim  # gives dimension of array

1

In [219]:
a.shape

(5,)

In [220]:
len(a)

5

In [221]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [222]:
b.ndim

2

In [223]:
# This will throw an error
c=np.array([[0,1,2],[[3,4,5,6]]])
c

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [224]:
b.shape

(2, 3)

In [225]:
len(b)  #return the size of the first dimensions

2

In [226]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])  #3D array
# List-->List-->List
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

  4------5
 /|    / |
/ |   /  |
0----1 --|
| |    | |
| 6    7 |
| |    | |
2------3-|

In [227]:
c.ndim

3

In [228]:
len(c)

2

In [229]:
c.shape  #gives tuple. Len,Breadth<depth

(2, 2, 2)

In [230]:
# 1D array called Vector
# 2D array called Matrix
# ND array is called Tensors

In [231]:
#other way to create numpy array
b=np.arange(2,20,3) #start, exclusive end ,step
b

array([ 2,  5,  8, 11, 14, 17])

In [232]:
# Another way to create numpy array
a=np.linspace(1,2,6) # start,end ,number of points
a  # divides a in 6 equal distance points that's why called linspace

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [233]:
# common arrays
a=np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [234]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [235]:
a=np.ones((4,4)) # here (4,4) is tuple means ones function argument is tuple
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [236]:
# Creation of Identity matrix
#diagonal elements are 1 and rest are zeros
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [237]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [238]:
# Create array using diag function
a=np.diag([3,4,5,6])  # non diagonal elemets are zeros
a

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [239]:
np.diag(a) # Extract Diagonal Elements

array([3, 4, 5, 6])

In [240]:
# create array using random

# create an array of the given shape and populate it with random samples
a=np.random.rand(4)   # random is package9module) and rand is function
a  # here random numbers are Uniform distributed random numbers
# other type of random number are also there like "Guassian or standard normal random numbers"

array([0.17086899, 0.63974271, 0.48817856, 0.65622249])

In [241]:
a=np.random.randn(4) # guassian random numbers generete krse
a  # randn means random normal

array([-0.51810363, -0.37895731, -0.77122162, -3.10329798])

<h2> Basic DataTypes </h2>

In [242]:
a=np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]

dtype('int64')

In [243]:
# you can explicitly specify which datatype you want
a=np.arange(10,dtype='float64')
a
# here dot means numbers are in float

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [244]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

dtype('float64')

In [245]:
# by default zeros and ones function's values are in float

In [246]:
# Complex datatype
d=np.array([1+2j,2+4j])
d.dtype

dtype('complex128')

In [247]:
# Boolean datatype
b=np.array([True,True,False])
b.dtype

dtype('bool')

In [248]:
# String Numpy Array
s=np.array(['Ram','Rahim'])
s.dtype

dtype('<U5')

<h2> Indexing and Slicing </h2>

In [249]:
# how to access elements
a=np.arange(10)
a[5] # indices starts from 0 like C/C++

5

In [250]:
#for multidimentional arrays, indexes are tuples of integers.
a=np.diag([1,2,3])
print(a[2,2])

3

In [251]:
a[2,1]=5 # Assigning value at position 3rd row and 2nd col
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [252]:
# Slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [253]:
a[1:8:2] # [Start_index, End_Index(exclusive), Step]
#getting subarray using slicing

array([1, 3, 5, 7])

In [254]:
# we can also combine assignment and slicing
a=np.arange(10)
a[5:]=10  # from index 5 onwards put all elemets as 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [255]:
b=np.arange(5)
a[5:]=b[::-1] # Assigning
a
b[::-1] #start=0, end=len, -1 means reverse

array([4, 3, 2, 1, 0])

<h3> Copies and Views</h3>

A slicing operation creates a view on original array, which is just a way of accessing array data. thus the original array is not copied in memory. you can  use np.may_share_memory() to check if two arrays share the same memory blockk

In [256]:
#When modifying the view, the original array is modified as well
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [257]:
b=a[::2]  # a and b both are pointing to same array 0,1,2..9 for memory optimization but b is actually sub array. so here copy of aray is not used.
b

array([0, 2, 4, 6, 8])

In [258]:
np.shares_memory(a,b)

True

In [259]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [260]:
# eventhough we modified b, it updates 'a' because both shares same memory
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [261]:
a=np.arange(10)
c=a[::2].copy()  # Force a copy
c

array([0, 2, 4, 6, 8])

In [262]:
np.shares_memory(a,c)  # we forcelly say not to share memory.. a and c are pointing other locations. Now if u modified 'c'; then 'a' will not get updated

False

In [263]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [264]:
a  # a is not updating

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3> Fancy Indexing </h3>

Numpy Array can be indexed with slices, but also with boolean or integer arrays(masks). this method is called fancy indexing. It creates copies not views.

In [265]:
# using boolean mask
a=np.random.randint(0,20,15)  # generates random number between 0 to 20 and generates 15 such numbers which all are of integer
print(a.dtype)
a

int64

array([16,  9,  5, 19, 16, 16,  3, 11, 11,  4,  0,  3,  4, 16,  1])

In [266]:
mask=(a%2==0)
mask

array([ True, False, False, False,  True,  True, False, False, False,
        True,  True, False,  True,  True, False])

In [267]:
extract_from_a=a[mask]  # where the a%2==0 become true ; those values come in extract_from_a
extract_from_a

array([16, 16, 16,  4,  0,  4, 16])

In [268]:
# indexing with a mask can be very useful to assign a new value to a sub array
a[mask]=-1
a # all even numbers repleced by -1

array([-1,  9,  5, 19, -1, -1,  3, 11, 11, -1, -1,  3, -1, -1,  1])

In [269]:
# indexing with an array of integeres
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [270]:
a[[2,3,2,4,2]] # here we are giving indices in the list like 2nd index,3rd index, again 2nd index and so on and print their values

array([20, 30, 20, 40, 20])

In [271]:
a[[9,7]]=-200  # on index 9 and 7 .. replace with -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

<h2> Operations </h2>

In [272]:
a=np.array([1,2,3,4])
a+1   # 1 get added in every element

array([2, 3, 4, 5])

In [273]:
a**2

array([ 1,  4,  9, 16])

In [274]:
a

array([1, 2, 3, 4])

In [275]:
# All arithmetic operates element wise
b=np.ones(4)+1
b

array([2., 2., 2., 2.])

In [276]:
a-b

array([-1.,  0.,  1.,  2.])

In [277]:
a*b  # component wise multiplication

array([2., 4., 6., 8.])

In [278]:
#Matrix Multiplication
c=np.diag([1,2,3,4])
print(c*c)
print("----------------")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
----------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]

In [279]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,0],[2,1]])
x*y  # element wise multiplication

array([[1, 0],
       [6, 4]])

In [280]:
x.dot(y)  #matrix mux bcz in algebra we use A.A to show  multiplication

array([[ 5,  2],
       [11,  4]])

In [281]:
a=np.array([1,2,3])
b=np.array([2,2,3])
a==b  # element wise comparision

array([False,  True,  True])

In [282]:
a>b

array([False, False, False])

In [283]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [284]:
np.array_equal(a,c)

True

In [285]:
# Logical Operations
a=np.array([1,1,0,0])
a.dtype

dtype('int64')

In [286]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [287]:
np.logical_and(a,b)

array([ True, False, False, False])

In [288]:
np.logical_xor(a,b)

array([False,  True,  True, False])

In [289]:
#transcendental Operations
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [290]:
np.log(a)  # element wise log

<ipython-input-290-d2512a61ee40>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)  # element wise log

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [291]:
np.exp(a) # exponent i.e. e power x (e=2.71)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [292]:
#shape mismatch
# throw an error
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,)

In [293]:
# basic reductions
x=np.array([1,2,3,4])
np.sum(x)

10

In [294]:
# sum by ros and by columns
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [295]:
x.sum(axis=0)  # axis 0 means it will do column wise sum

array([3, 3])

In [296]:
x.sum(axis=1) # means will do sum row wise

array([2, 4])

In [297]:
x=np.array([1,3,2])
x.min()

1

In [298]:
x.max()

3

In [299]:
x.argmin() # index of minimum element

0

In [300]:
x.argmax()

1

In [301]:
# logical operations
np.all([True,False,True]) # if all elements are true then return true but if one of element is false..it will return false
# logical and

False

In [302]:
np.any([True,False,True])  # logical or

True

In [303]:
a=np.zeros((3,4))

In [304]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [305]:
np.all(a==a)

True

In [306]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
print(a<=b)   # ama for loop b use na krvi pde
((a<=b) & (b<=c)).all()

[ True  True  True  True]

True

In [307]:
# Statistics
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [308]:
np.median(x)

1.5

In [309]:
np.median(y,axis=-1) #last axis

array([2., 5.])

In [310]:
x.std() # full population  standard deviation

0.82915619758885

<h2> Example</h2>

Data in populations.txt describes the population of hares and lynxes (and carrots) in northern canada duing 20 years

In [315]:
data=np.loadtxt('/content/Book1.txt')

In [316]:
data

array([[ 1990., 30000., 40300., 48000.],
       [ 1901., 47200., 57000., 45000.],
       [ 1902., 70200., 76600., 43544.],
       [ 1903., 77400., 52300., 54677.],
       [ 1904., 36300., 19500., 50000.],
       [ 1905., 20600., 11200., 43222.],
       [ 1906., 18100.,  7600., 44565.],
       [ 1907., 21400., 77400., 32333.],
       [ 1908., 22000., 36300., 56788.],
       [ 1909., 25400., 20600., 54000.],
       [ 1910., 27100., 18100., 60000.],
       [ 1911., 40300., 19500., 56000.],
       [ 1912., 57000., 11200., 45000.],
       [ 1913., 76600.,  7600., 34000.],
       [ 1914., 52300., 14600., 56000.],
       [ 1915., 19500., 16200., 23456.],
       [ 1916., 11200., 20600., 56789.],
       [ 1917.,  7600., 18100., 34567.],
       [ 1918., 14600., 21400., 34500.],
       [ 1919., 16200., 22000., 45000.],
       [ 1920., 24700., 25400., 45000.]])

In [314]:
year,hares,lynxes,carrots=data.T  # columns to varaible
print(year)

[1990. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]

In [317]:
#The mean population over time
populations=data[:,1:]    #[:,] means take all rows but [:,1:] ma 1: means from columns 1 to last. so take all rows from column 1 to end column
populations

array([[30000., 40300., 48000.],
       [47200., 57000., 45000.],
       [70200., 76600., 43544.],
       [77400., 52300., 54677.],
       [36300., 19500., 50000.],
       [20600., 11200., 43222.],
       [18100.,  7600., 44565.],
       [21400., 77400., 32333.],
       [22000., 36300., 56788.],
       [25400., 20600., 54000.],
       [27100., 18100., 60000.],
       [40300., 19500., 56000.],
       [57000., 11200., 45000.],
       [76600.,  7600., 34000.],
       [52300., 14600., 56000.],
       [19500., 16200., 23456.],
       [11200., 20600., 56789.],
       [ 7600., 18100., 34567.],
       [14600., 21400., 34500.],
       [16200., 22000., 45000.],
       [24700., 25400., 45000.]])

In [319]:
#sample std devaitions
populations.std(axis=0) #axis=0 means compute by rows

array([20897.90645809, 20359.28420929,  9535.05159483])

In [320]:
#which species has the highest population each year
np.argmax(populations,axis=1)
#means axis=1 etle row wise lese ne first row mathi kai value max che eno index return krse then 2nd row mathi je value max hse eno index return krde

array([2, 1, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2])

<h2>Broadcasting</h2>

In [330]:
a=np.tile(np.arange(0,40,10),(3,1))  #(3,1) means replicate 0,10,20,30 three times in terms of rows  and 1 means replicate column only once
print(a)
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]

In [326]:
c=np.tile(np.arange(0,40,10),(3,2))  # replicate rows 3 times and replicate columns twice
c

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [327]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [331]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [332]:
a+b  # a is 4X3 and b is 1X3
##interanlly it replicates as columns is matching

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [333]:
a=np.arange(0,40,10)
a.shape

(4,)

In [334]:
a=a[:,np.newaxis]  # adds a new axis in 2D array
# aa na kro to 1D to 2D ma nai fre ne error avse
a.shape

(4, 1)

In [335]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [336]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

<h3> Array Shape Manipulation</h3.

In [338]:
#Flattening
a=np.array([[1,2,3],[4,5,6]])
a.ravel() # return a flatten continuous array

array([1, 2, 3, 4, 5, 6])

In [339]:
a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [340]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [342]:
#Reshaping
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]

In [343]:
b=a.ravel()

In [345]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [346]:
b=b.reshape((3,2))

In [347]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [350]:
b[0,0]=100
print(b)
print(a)

[[100   2]
 [  3   4]
 [  5   6]]
[[100   2   3]
 [  4   5   6]]

<h3>Note and Beware:Reshape may also return a copy</h3>
Numpy always optimize the memory

<h3> Adding a dimensions
---
indexing with the np.newaxis object allows us toadd an axis to an array.
newaxis is used to increase the dimensionof the existing array by one more dimensions,when used once thus,
1D will become 2D array,
2D array will become 3D array and so on
</h3>

In [354]:
z=np.array([1,2,3])
print(z.shape)
z

(3,)

array([1, 2, 3])

In [356]:
z=z[:,np.newaxis]

In [357]:
print(z.shape)
z

(3, 1)

array([[1],
       [2],
       [3]])

In [358]:
# Dimension Shuffling
a=np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [360]:
a=a.reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [361]:
a[0,2,1] # access of an element

5

In [365]:
#Resizing
a=np.arange(4)

In [367]:
a.resize((8,),refcheck=False)  # it resize in 8 elements but rest of elements are initiated as zero

In [370]:
# however it must reffered to somewhere else
b=a
b.resize((4,))   #will through an error

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [378]:
# sorting data
a=np.array([[3,2,1],[4,2,3]])
b=np.sort(a,axis=1)  # sorting along an axis
print(b)

[[1 2 3]
 [2 3 4]]

In [379]:
a.sort(axis=1)  #inplace sorting
#it modifies a
a

array([[1, 2, 3],
       [2, 3, 4]])

In [380]:
#sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)   #it sort and return its original indices..means pela 1 no index 2 hto then 2 no index 3
j

array([2, 3, 1, 0])

In [381]:
a[j]

array([1, 2, 3, 4])